<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <div class="sidebar">
            <div class="logo">
                <img src="Logo/Logo1.png" alt="Logo">
            </div>
            <ul>
                <li class="active">
                <a href="login.html">Admin Register or Login</a></li>
                <li><a href="textadmin2/admin_page.php">Second Page</a></li>
            </ul>
        </div>
        <div class="banner-container">
            <img src="Welcome to admIn panel.png" alt="Welcome to Admin panel">
        </div>
    </div>
    <script src="script.js"></script>
</body>
</html>
